#!/usr/bin/env python3
import argparse
import datetime as dt
import json
import random
import ssl
import sys
import urllib.error
import urllib.request
import uuid
# Tạo 1 topic auto cho course:
# python .\backend\scripts\create_topic_via_api.py --course-id "<course-guid>" -identity-cookie "HanziAnhVu.Identity=eyJ..." --insecure
# Tạo 5 topic auto:
# python .\backend\scripts\create_topic_via_api.py --course-id "<course-guid>" --count 5 -identity-cookie "HanziAnhVu.Identity=eyJ..." --insecure
# Tạo topic dạng Exam:
# python .\backend\scripts\create_topic_via_api.py --course-id "<course-guid>" --topic-type Exam --exam-year 2026 --exam-code "HSK-MOCK-01" --count 2 -identity-cookie "HanziAnhVu.Identity=eyJ..." --insecure
# Chỉ xem payload:
# python .\backend\scripts\create_topic_via_api.py --course-id "<course-guid>" --count 3 --dry-run
def utc_stamp() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")


def http_request(
    method: str,
    url: str,
    headers: dict[str, str],
    body: bytes | None,
    insecure: bool,
) -> tuple[int, bytes]:
    req = urllib.request.Request(url=url, method=method, headers=headers, data=body)
    context = None
    if insecure:
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
    with urllib.request.urlopen(req, context=context, timeout=30) as resp:
        return resp.getcode(), resp.read()


def extract_cookie_pair(raw: str, default_name: str | None = None) -> str:
    value = raw.strip()
    if not value:
        raise ValueError("Cookie value must not be empty.")

    if ";" in value:
        value = value.split(";", 1)[0].strip()

    if "=" not in value:
        if default_name is None:
            raise ValueError(
                "Cookie must be in 'name=value' format when no default cookie name is provided."
            )
        return f"{default_name}={value}"

    name, cookie_value = value.split("=", 1)
    name = name.strip()
    cookie_value = cookie_value.strip()
    if not name or not cookie_value:
        raise ValueError("Cookie must contain both name and value.")

    return f"{name}={cookie_value}"


def build_cookie_header(args: argparse.Namespace) -> str | None:
    pairs: list[str] = []

    if args.cookie:
        for item in args.cookie:
            pairs.append(extract_cookie_pair(item))

    if args.identity_cookie:
        pairs.append(extract_cookie_pair(args.identity_cookie, "HanziAnhVu.Identity"))

    if args.refresh_cookie:
        pairs.append(extract_cookie_pair(args.refresh_cookie, "HanziAnhVu.Refresh"))

    if args.cookie_header:
        raw_header = args.cookie_header.strip()
        if raw_header:
            for part in raw_header.split(";"):
                part = part.strip()
                if not part:
                    continue
                pairs.append(extract_cookie_pair(part))

    if not pairs:
        return None

    return "; ".join(pairs)


def build_endpoint(base_url: str, api_version: int) -> str:
    return f"{base_url.rstrip('/')}/api/lesson/v{api_version}/topic"


def build_topic_payload(
    args: argparse.Namespace,
    index: int,
    rng: random.Random,
) -> dict[str, object]:
    topic_type = args.topic_type

    if args.title:
        title = args.title.strip()
        if args.count > 1:
            title = f"{title} #{index}"
    else:
        title = f"AUTO {topic_type} - {utc_stamp()}-{index:03d}"

    if args.description:
        description = args.description.strip()
    else:
        description = (
            "Auto-generated by create_topic_via_api.py "
            f"at {utc_stamp()} (item {index})."
        )

    estimated_time_minutes = (
        args.estimated_time_minutes
        if args.estimated_time_minutes is not None
        else rng.randint(10, 45)
    )

    payload: dict[str, object] = {
        "CourseId": args.course_id,
        "Title": title,
        "Description": description,
        "TopicType": topic_type,
        "EstimatedTimeMinutes": estimated_time_minutes,
    }

    if topic_type == "Exam":
        exam_year = args.exam_year if args.exam_year is not None else dt.datetime.now().year
        exam_code = (
            args.exam_code.strip()
            if args.exam_code
            else f"EX-{utc_stamp()}-{index:03d}"
        )
        payload["ExamYear"] = exam_year
        payload["ExamCode"] = exam_code

    return payload


def print_response(body: bytes) -> None:
    content = body.decode("utf-8", errors="replace")
    if not content:
        return

    try:
        parsed = json.loads(content)
        print(json.dumps(parsed, indent=2, ensure_ascii=False))
    except json.JSONDecodeError:
        print(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create topic(s) via backend Lesson API. "
            "CourseId is required and payload can be auto-generated."
        )
    )

    parser.add_argument(
        "--base-url",
        default="https://localhost:1907",
        help="Backend base URL, for example https://localhost:1907",
    )
    parser.add_argument(
        "--api-version",
        type=int,
        default=1,
        help="Lesson API version used in path /api/lesson/v{version}/topic",
    )

    parser.add_argument(
        "--course-id",
        required=True,
        help="Course ID (GUID). Required.",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="Number of topics to create. Default is 1.",
    )
    parser.add_argument("--title", help="Topic title. Auto-generated if omitted.")
    parser.add_argument(
        "--description",
        help="Topic description. Auto-generated if omitted.",
    )
    parser.add_argument(
        "--topic-type",
        default="Learning",
        choices=["Learning", "Exam"],
        help="Topic type. Default is Learning.",
    )
    parser.add_argument(
        "--estimated-time-minutes",
        type=int,
        help="Estimated time in minutes. Random 10..45 if omitted.",
    )
    parser.add_argument(
        "--exam-year",
        type=int,
        help="Exam year (used when topic-type=Exam).",
    )
    parser.add_argument(
        "--exam-code",
        help="Exam code (used when topic-type=Exam). Auto-generated if omitted.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        help="Random seed for deterministic auto-generated values.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print generated payload(s), do not call API.",
    )

    parser.add_argument(
        "-identity-cookie",
        "--identity-cookie",
        help=(
            "Identity cookie value, 'name=value', or full Set-Cookie string. "
            "If only token is provided, script uses name HanziAnhVu.Identity."
        ),
    )
    parser.add_argument(
        "-refresh-cookie",
        "--refresh-cookie",
        help=(
            "Refresh cookie value, 'name=value', or full Set-Cookie string. "
            "If only token is provided, script uses name HanziAnhVu.Refresh."
        ),
    )
    parser.add_argument(
        "--cookie",
        action="append",
        help="Extra cookie in name=value format. Can be specified multiple times.",
    )
    parser.add_argument(
        "--cookie-header",
        help="Raw cookie header string, for example 'a=1; b=2'.",
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Skip TLS cert validation (local/self-signed only).",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.count <= 0:
        print("count must be > 0", file=sys.stderr)
        return 2

    try:
        course_id = str(uuid.UUID(args.course_id))
        args.course_id = course_id
    except ValueError:
        print("course-id must be a valid GUID.", file=sys.stderr)
        return 2

    if args.estimated_time_minutes is not None and args.estimated_time_minutes <= 0:
        print("estimated-time-minutes must be > 0", file=sys.stderr)
        return 2

    endpoint = build_endpoint(args.base_url, args.api_version)

    headers: dict[str, str] = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    cookie_header = build_cookie_header(args)
    if cookie_header:
        headers["Cookie"] = cookie_header

    rng = random.Random(args.seed)
    payloads = [build_topic_payload(args, i + 1, rng) for i in range(args.count)]

    if args.dry_run:
        print(f"Request URL: {endpoint}")
        print(json.dumps(payloads, indent=2, ensure_ascii=False))
        return 0

    failed = 0
    for idx, payload in enumerate(payloads, start=1):
        body = json.dumps(payload).encode("utf-8")
        print(f"--- Create topic {idx}/{len(payloads)} ---")
        print(f"Request URL: {endpoint}")
        print(json.dumps(payload, indent=2, ensure_ascii=False))

        try:
            status, response_body = http_request(
                method="POST",
                url=endpoint,
                headers=headers,
                body=body,
                insecure=args.insecure,
            )
            print(f"Status: {status}")
            print_response(response_body)
        except urllib.error.HTTPError as ex:
            failed += 1
            body_text = (
                ex.read().decode("utf-8", errors="replace")
                if hasattr(ex, "read")
                else ""
            )
            print(f"HTTP error {ex.code}", file=sys.stderr)
            if body_text:
                print(body_text, file=sys.stderr)
        except urllib.error.URLError as ex:
            failed += 1
            print(f"Failed to connect to {endpoint}: {ex}", file=sys.stderr)
        except Exception as ex:
            failed += 1
            print(f"Unexpected error: {ex}", file=sys.stderr)

    if failed > 0:
        print(f"Done with {failed} failed request(s).", file=sys.stderr)
        return 1

    print(f"Done. Created {len(payloads)} topic(s) successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
