#!/usr/bin/env python3
import argparse
import datetime as dt
import json
import random
import ssl
import sys
import urllib.error
import urllib.request
# Ví dụ dùng ngay:

# Tự sinh body hoàn toàn, tạo 1 course
# python .\create_course_via_api.py -identity-cookie "HanziAnhVu.Identity=eyJ..." --insecure

# Tự sinh body, tạo 5 course
# python .\create_course_via_api.py -identity-cookie "HanziAnhVu.Identity=eyJ..." --count 5 --insecure

# Xem trước body không gọi API
# python .\create_course_via_api.py -identity-cookie "HanziAnhVu.Identity=eyJ..." --count 3 --dry-run --insecure

# Muốn cố định level nhưng vẫn auto title/description
# python .\create_course_via_api.py -identity-cookie "HanziAnhVu.Identity=eyJ..." --hsk-level 4 --count 2 --insecure

def utc_stamp() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d-%H%M%S")

def http_request(
    method: str,
    url: str,
    headers: dict[str, str],
    body: bytes | None,
    insecure: bool,
) -> tuple[int, bytes]:
    req = urllib.request.Request(url=url, method=method, headers=headers, data=body)
    context = None
    if insecure:
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
    with urllib.request.urlopen(req, context=context, timeout=30) as resp:
        return resp.getcode(), resp.read()


def extract_cookie_pair(raw: str, default_name: str | None = None) -> str:
    value = raw.strip()
    if not value:
        raise ValueError("Cookie value must not be empty.")

    if ";" in value:
        value = value.split(";", 1)[0].strip()

    if "=" not in value:
        if default_name is None:
            raise ValueError(
                "Cookie must be in 'name=value' format when no default cookie name is provided."
            )
        return f"{default_name}={value}"

    name, cookie_value = value.split("=", 1)
    name = name.strip()
    cookie_value = cookie_value.strip()
    if not name or not cookie_value:
        raise ValueError("Cookie must contain both name and value.")

    return f"{name}={cookie_value}"


def build_cookie_header(args: argparse.Namespace) -> str | None:
    pairs: list[str] = []

    if args.cookie:
        for item in args.cookie:
            pairs.append(extract_cookie_pair(item))

    if args.identity_cookie:
        pairs.append(extract_cookie_pair(args.identity_cookie, "HanziAnhVu.Identity"))

    if args.refresh_cookie:
        pairs.append(extract_cookie_pair(args.refresh_cookie, "HanziAnhVu.Refresh"))

    if args.cookie_header:
        raw_header = args.cookie_header.strip()
        if raw_header:
            for part in raw_header.split(";"):
                part = part.strip()
                if not part:
                    continue
                pairs.append(extract_cookie_pair(part))

    if not pairs:
        return None

    return "; ".join(pairs)


def build_endpoint(base_url: str, api_version: int) -> str:
    return f"{base_url.rstrip('/')}/api/lesson/v{api_version}/course"


def build_course_payload(
    args: argparse.Namespace,
    index: int,
    rng: random.Random,
) -> dict[str, object]:
    hsk_level = args.hsk_level if args.hsk_level is not None else rng.randint(1, 6)

    if args.title:
        title = args.title.strip()
        if args.count > 1:
            title = f"{title} #{index}"
    else:
        title = f"AUTO HSK {hsk_level} - {utc_stamp()}-{index:03d}"

    if args.description:
        description = args.description.strip()
    else:
        description = (
            "Auto-generated by create_course_via_api.py "
            f"at {utc_stamp()} (item {index})."
        )

    return {
        "Title": title,
        "Description": description,
        "HskLevel": hsk_level,
    }


def print_response(body: bytes) -> None:
    content = body.decode("utf-8", errors="replace")
    if not content:
        return

    try:
        parsed = json.loads(content)
        print(json.dumps(parsed, indent=2, ensure_ascii=False))
    except json.JSONDecodeError:
        print(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create a new course via backend Lesson API. "
            "Supports Cookie auth (HanziAnhVu.Identity) for protected endpoints."
        )
    )

    parser.add_argument(
        "--base-url",
        default="https://localhost:1907",
        help="Backend base URL, for example https://localhost:1907",
    )
    parser.add_argument(
        "--api-version",
        type=int,
        default=1,
        help="Lesson API version used in path /api/lesson/v{version}/course",
    )

    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="Number of courses to create. Default is 1.",
    )
    parser.add_argument("--title", help="Course title. Auto-generated if omitted.")
    parser.add_argument(
        "--description",
        help="Course description. Auto-generated if omitted.",
    )
    parser.add_argument(
        "--hsk-level",
        type=int,
        help="HSK level (integer). Random 1..6 if omitted.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        help="Random seed for deterministic auto-generated values.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print generated payload(s), do not call API.",
    )

    parser.add_argument(
        "-identity-cookie",
        "--identity-cookie",
        help=(
            "Identity cookie value, 'name=value', or full Set-Cookie string. "
            "If only token is provided, script uses name HanziAnhVu.Identity."
        ),
    )
    parser.add_argument(
        "-refresh-cookie",
        "--refresh-cookie",
        help=(
            "Refresh cookie value, 'name=value', or full Set-Cookie string. "
            "If only token is provided, script uses name HanziAnhVu.Refresh."
        ),
    )
    parser.add_argument(
        "--cookie",
        action="append",
        help="Extra cookie in name=value format. Can be specified multiple times.",
    )
    parser.add_argument(
        "--cookie-header",
        help="Raw cookie header string, for example 'a=1; b=2'.",
    )
    parser.add_argument(
        "--insecure",
        action="store_true",
        help="Skip TLS cert validation (local/self-signed only).",
    )

    return parser.parse_args()


def main() -> int:
    args = parse_args()

    if args.count <= 0:
        print("count must be > 0", file=sys.stderr)
        return 2

    if args.hsk_level is not None and args.hsk_level < 1:
        print("hsk-level must be >= 1", file=sys.stderr)
        return 2

    endpoint = build_endpoint(args.base_url, args.api_version)

    headers: dict[str, str] = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    cookie_header = build_cookie_header(args)
    if cookie_header:
        headers["Cookie"] = cookie_header

    rng = random.Random(args.seed)
    payloads = [build_course_payload(args, i + 1, rng) for i in range(args.count)]

    if args.dry_run:
        print(f"Request URL: {endpoint}")
        print(json.dumps(payloads, indent=2, ensure_ascii=False))
        return 0

    failed = 0
    for idx, payload in enumerate(payloads, start=1):
        body = json.dumps(payload).encode("utf-8")
        print(f"--- Create course {idx}/{len(payloads)} ---")
        print(f"Request URL: {endpoint}")
        print(json.dumps(payload, indent=2, ensure_ascii=False))

        try:
            status, response_body = http_request(
                method="POST",
                url=endpoint,
                headers=headers,
                body=body,
                insecure=args.insecure,
            )
            print(f"Status: {status}")
            print_response(response_body)
        except urllib.error.HTTPError as ex:
            failed += 1
            body_text = (
                ex.read().decode("utf-8", errors="replace")
                if hasattr(ex, "read")
                else ""
            )
            print(f"HTTP error {ex.code}", file=sys.stderr)
            if body_text:
                print(body_text, file=sys.stderr)
        except urllib.error.URLError as ex:
            failed += 1
            print(f"Failed to connect to {endpoint}: {ex}", file=sys.stderr)
        except Exception as ex:
            failed += 1
            print(f"Unexpected error: {ex}", file=sys.stderr)

    if failed > 0:
        print(f"Done with {failed} failed request(s).", file=sys.stderr)
        return 1

    print(f"Done. Created {len(payloads)} course(s) successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
