import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { auth } from "@/auth";
import NextAuthWrapper from "@/lib/next.auth.wrapper";
import QueryClientProviderWrapper from "@/lib/query.client.provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    if (session?.user) {
        // TODO: Look into https://react.dev/reference/react/experimental_taintObjectReference
        // filter out sensitive data before passing to client.
        session.user = {
            ...session.user,
            // Keep custom fields like roles, userId, userName if needed on client
        };
    }

    return (
        <html lang="en" className={cn("font-sans", inter.variable)}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <NextAuthWrapper session={session}>
                    <QueryClientProviderWrapper>
                        {children}
                    </QueryClientProviderWrapper>
                </NextAuthWrapper>
            </body>
        </html>
    );
}
