import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/shared/lib/utils";
import { auth } from "@/auth";
import NextAuthWrapper from "@/shared/lib/next.auth.wrapper";
import QueryClientProviderWrapper from "@/shared/lib/query.client.provider";
import { TooltipProvider } from "@/shared/components/ui/tooltip";
import { Toaster } from "@/shared/components/ui/sonner";
import { AuthSessionListener } from "@/modules/auth/components/auth-session-listener";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    if (session?.user) {
        session.user = {
            ...session.user,
            // Keep custom fields like roles, userId, userName if needed on client
        };
    }
    // console.log("Session in RootLayout:", session);

    return (
        <html lang="en" className={cn("font-sans", inter.variable)}>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <QueryClientProviderWrapper>
                    <NextAuthWrapper session={session}>
                        <AuthSessionListener />
                        <TooltipProvider>
                            {children}
                            <Toaster richColors position="top-right" />
                        </TooltipProvider>
                    </NextAuthWrapper>
                </QueryClientProviderWrapper>
            </body>
        </html>
    );
}
