# This workflow builds the backend, pushes a Docker image, and deploys to VPS

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore ./backend/src/hanzi-anhvu-hsk/HanziAnhVuHsk.Api.csproj
      - name: Build project
        run: dotnet build --no-restore --configuration Release ./backend/src/hanzi-anhvu-hsk/HanziAnhVuHsk.Api.csproj

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        # echo là để tránh lộ mật khẩu trong logs
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hanzi-app:latest -f backend/src/hanzi-anhvu-hsk/Dockerfile backend/src/hanzi-anhvu-hsk
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hanzi-app:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to VPS
        # appleboy/ssh-action@master uses SSH key authentication to run commands on the remote server.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          host_key_check: false
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/hanzi-app:latest
            docker stop hanzi-app || true
            docker rm hanzi-app || true
            docker run -d -p 80:8080 --name hanzi-app ${{ secrets.DOCKER_USERNAME }}/hanzi-app:latest
